
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Leonardo
 */
public class Termo extends javax.swing.JFrame {

    String[] palavras = {"cinco", "outra"};
    String palavraSorteada = "";

    /**
     * Creates new form Termo
     */
    public Termo() {
        initComponents();
        sortearPalavra();
    }

    private void sortearPalavra() {
        Random r = new Random();
        int indicePalavra = r.nextInt(palavras.length);
        System.out.println(palavras[indicePalavra]);
        palavraSorteada = palavras[indicePalavra];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfa1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtentar = new javax.swing.JButton();
        jbq = new javax.swing.JButton();
        jtfa2 = new javax.swing.JTextField();
        jtfa3 = new javax.swing.JTextField();
        jtfa4 = new javax.swing.JTextField();
        jtfa0 = new javax.swing.JTextField();
        jtfb2 = new javax.swing.JTextField();
        jtfb3 = new javax.swing.JTextField();
        jtfb4 = new javax.swing.JTextField();
        jtfb5 = new javax.swing.JTextField();
        jtfb1 = new javax.swing.JTextField();
        jtfc2 = new javax.swing.JTextField();
        jtfc3 = new javax.swing.JTextField();
        jtfc4 = new javax.swing.JTextField();
        jtfc5 = new javax.swing.JTextField();
        jtfc1 = new javax.swing.JTextField();
        txttentativa15 = new javax.swing.JTextField();
        txttentativa16 = new javax.swing.JTextField();
        txttentativa17 = new javax.swing.JTextField();
        txttentativa18 = new javax.swing.JTextField();
        txttentativa19 = new javax.swing.JTextField();
        txttentativa20 = new javax.swing.JTextField();
        txttentativa21 = new javax.swing.JTextField();
        txttentativa22 = new javax.swing.JTextField();
        txttentativa23 = new javax.swing.JTextField();
        txttentativa24 = new javax.swing.JTextField();
        txttentativa25 = new javax.swing.JTextField();
        txttentativa26 = new javax.swing.JTextField();
        txttentativa27 = new javax.swing.JTextField();
        txttentativa28 = new javax.swing.JTextField();
        txttentativa29 = new javax.swing.JTextField();
        jbw = new javax.swing.JButton();
        jbe = new javax.swing.JButton();
        jbt = new javax.swing.JButton();
        jby = new javax.swing.JButton();
        jbr = new javax.swing.JButton();
        jbi = new javax.swing.JButton();
        jbo = new javax.swing.JButton();
        jbu = new javax.swing.JButton();
        jbs = new javax.swing.JButton();
        jbd = new javax.swing.JButton();
        jba = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jbg = new javax.swing.JButton();
        jbh = new javax.swing.JButton();
        jbf = new javax.swing.JButton();
        jbk = new javax.swing.JButton();
        jbl = new javax.swing.JButton();
        jbj = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jbp = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfa1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TERMULANDO");

        jbtentar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtentar.setText("TENTAR");
        jbtentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtentarActionPerformed(evt);
            }
        });

        jbq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbq.setText("Q");
        jbq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbqActionPerformed(evt);
            }
        });

        jtfa2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfa2ActionPerformed(evt);
            }
        });

        jtfa3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfa3ActionPerformed(evt);
            }
        });

        jtfa4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfa4ActionPerformed(evt);
            }
        });

        jtfa0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfa0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfa0ActionPerformed(evt);
            }
        });

        jtfb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfb2ActionPerformed(evt);
            }
        });

        jtfb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfb3ActionPerformed(evt);
            }
        });

        jtfb4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfb4ActionPerformed(evt);
            }
        });

        jtfb5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfb5ActionPerformed(evt);
            }
        });

        jtfb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfb1ActionPerformed(evt);
            }
        });

        jtfc2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc2ActionPerformed(evt);
            }
        });

        jtfc3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc3ActionPerformed(evt);
            }
        });

        jtfc4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc4ActionPerformed(evt);
            }
        });

        jtfc5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc5ActionPerformed(evt);
            }
        });

        jtfc1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfc1ActionPerformed(evt);
            }
        });

        txttentativa15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa15ActionPerformed(evt);
            }
        });

        txttentativa16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa16ActionPerformed(evt);
            }
        });

        txttentativa17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa17ActionPerformed(evt);
            }
        });

        txttentativa18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa18ActionPerformed(evt);
            }
        });

        txttentativa19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa19ActionPerformed(evt);
            }
        });

        txttentativa20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa20ActionPerformed(evt);
            }
        });

        txttentativa21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa21ActionPerformed(evt);
            }
        });

        txttentativa22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa22ActionPerformed(evt);
            }
        });

        txttentativa23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa23ActionPerformed(evt);
            }
        });

        txttentativa24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa24ActionPerformed(evt);
            }
        });

        txttentativa25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa25ActionPerformed(evt);
            }
        });

        txttentativa26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa26ActionPerformed(evt);
            }
        });

        txttentativa27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa27ActionPerformed(evt);
            }
        });

        txttentativa28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa28ActionPerformed(evt);
            }
        });

        txttentativa29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttentativa29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttentativa29ActionPerformed(evt);
            }
        });

        jbw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbw.setText("W");
        jbw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbwActionPerformed(evt);
            }
        });

        jbe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbe.setText("E");
        jbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeActionPerformed(evt);
            }
        });

        jbt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbt.setText("T");
        jbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtActionPerformed(evt);
            }
        });

        jby.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jby.setText("Y");
        jby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbyActionPerformed(evt);
            }
        });

        jbr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbr.setText("R");
        jbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrActionPerformed(evt);
            }
        });

        jbi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbi.setText("I");
        jbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbiActionPerformed(evt);
            }
        });

        jbo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbo.setText("O");
        jbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboActionPerformed(evt);
            }
        });

        jbu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbu.setText("U");
        jbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuActionPerformed(evt);
            }
        });

        jbs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbs.setText("S");
        jbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsActionPerformed(evt);
            }
        });

        jbd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbd.setText("D");
        jbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdActionPerformed(evt);
            }
        });

        jba.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jba.setText("A");
        jba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setText("X");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton14.setText("C");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton15.setText("Z");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jbg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbg.setText("G");
        jbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgActionPerformed(evt);
            }
        });

        jbh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbh.setText("H");
        jbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhActionPerformed(evt);
            }
        });

        jbf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbf.setText("F");
        jbf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfActionPerformed(evt);
            }
        });

        jbk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbk.setText("K");
        jbk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkActionPerformed(evt);
            }
        });

        jbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbl.setText("L");
        jbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblActionPerformed(evt);
            }
        });

        jbj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbj.setText("J");
        jbj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbjActionPerformed(evt);
            }
        });

        jButton22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton22.setText("B");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton23.setText("N");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton24.setText("V");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton27.setText("M");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jbp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbp.setText("P");
        jbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpActionPerformed(evt);
            }
        });

        jButton26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton26.setText("<");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txttentativa24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttentativa20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttentativa21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttentativa22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txttentativa23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfb1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfb2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfb3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfb4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfb5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfa0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfa2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfa3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfa4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfc1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfc2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfc3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfc4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfc5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txttentativa19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttentativa15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttentativa16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttentativa17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttentativa18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txttentativa29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttentativa25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttentativa26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttentativa27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttentativa28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jba)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbl)
                                .addGap(18, 18, 18)
                                .addComponent(jButton26))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton27)
                                .addGap(18, 18, 18)
                                .addComponent(jbtentar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jby)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbp)))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfa1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfa2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfa3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfa4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfa0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfb2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfb3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfb4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfb5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfb1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfc2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfc3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfc4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfc5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfc1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttentativa15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttentativa20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttentativa25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttentativa29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbw, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbr, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jby, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jba, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbs, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtentar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfa1ActionPerformed

    private void jbtentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtentarActionPerformed
        // TODO add your handling code here:

        int quantidadeErros = 0;
        String palavraSecreta = "Cinco";
        int tentaivas = 0;
        String tentativa = "";

//        if (txttentativa.getText() != 5) {
//            JOptionPane.showMessageDialog(null, "A palavra deve conter 5 letras!");
//        }
        if (tentativa.equals(palavraSecreta)) {
            JOptionPane.showMessageDialog(null, "Acertou Parabéns");
        }
    }//GEN-LAST:event_jbtentarActionPerformed

    private void jbqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbqActionPerformed

    private void jtfa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfa2ActionPerformed

    private void jtfa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfa3ActionPerformed

    private void jtfa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfa4ActionPerformed

    private void jtfa0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfa0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfa0ActionPerformed

    private void jtfb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfb2ActionPerformed

    private void jtfb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfb3ActionPerformed

    private void jtfb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfb4ActionPerformed

    private void jtfb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfb5ActionPerformed

    private void jtfb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfb1ActionPerformed

    private void jtfc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc2ActionPerformed

    private void jtfc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc3ActionPerformed

    private void jtfc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc4ActionPerformed

    private void jtfc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc5ActionPerformed

    private void jtfc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfc1ActionPerformed

    private void txttentativa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa15ActionPerformed

    private void txttentativa16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa16ActionPerformed

    private void txttentativa17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa17ActionPerformed

    private void txttentativa18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa18ActionPerformed

    private void txttentativa19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa19ActionPerformed

    private void txttentativa20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa20ActionPerformed

    private void txttentativa21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa21ActionPerformed

    private void txttentativa22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa22ActionPerformed

    private void txttentativa23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa23ActionPerformed

    private void txttentativa24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa24ActionPerformed

    private void txttentativa25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa25ActionPerformed

    private void txttentativa26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa26ActionPerformed

    private void txttentativa27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa27ActionPerformed

    private void txttentativa28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa28ActionPerformed

    private void txttentativa29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttentativa29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttentativa29ActionPerformed

    private void jbwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbwActionPerformed

    private void jbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbeActionPerformed

    private void jbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtActionPerformed

    private void jbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbyActionPerformed

    private void jbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbrActionPerformed

    private void jbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbiActionPerformed

    private void jboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jboActionPerformed

    private void jbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuActionPerformed

    private void jbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbsActionPerformed

    private void jbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbdActionPerformed

    private void jbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbaActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbgActionPerformed

    private void jbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbhActionPerformed

    private void jbfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbfActionPerformed

    private void jbkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbkActionPerformed

    private void jblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblActionPerformed

    private void jbjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbjActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbpActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Termo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Termo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jba;
    private javax.swing.JButton jbd;
    private javax.swing.JButton jbe;
    private javax.swing.JButton jbf;
    private javax.swing.JButton jbg;
    private javax.swing.JButton jbh;
    private javax.swing.JButton jbi;
    private javax.swing.JButton jbj;
    private javax.swing.JButton jbk;
    private javax.swing.JButton jbl;
    private javax.swing.JButton jbo;
    private javax.swing.JButton jbp;
    private javax.swing.JButton jbq;
    private javax.swing.JButton jbr;
    private javax.swing.JButton jbs;
    private javax.swing.JButton jbt;
    private javax.swing.JButton jbtentar;
    private javax.swing.JButton jbu;
    private javax.swing.JButton jbw;
    private javax.swing.JButton jby;
    private javax.swing.JTextField jtfa0;
    private javax.swing.JTextField jtfa1;
    private javax.swing.JTextField jtfa2;
    private javax.swing.JTextField jtfa3;
    private javax.swing.JTextField jtfa4;
    private javax.swing.JTextField jtfb1;
    private javax.swing.JTextField jtfb2;
    private javax.swing.JTextField jtfb3;
    private javax.swing.JTextField jtfb4;
    private javax.swing.JTextField jtfb5;
    private javax.swing.JTextField jtfc1;
    private javax.swing.JTextField jtfc2;
    private javax.swing.JTextField jtfc3;
    private javax.swing.JTextField jtfc4;
    private javax.swing.JTextField jtfc5;
    private javax.swing.JTextField txttentativa15;
    private javax.swing.JTextField txttentativa16;
    private javax.swing.JTextField txttentativa17;
    private javax.swing.JTextField txttentativa18;
    private javax.swing.JTextField txttentativa19;
    private javax.swing.JTextField txttentativa20;
    private javax.swing.JTextField txttentativa21;
    private javax.swing.JTextField txttentativa22;
    private javax.swing.JTextField txttentativa23;
    private javax.swing.JTextField txttentativa24;
    private javax.swing.JTextField txttentativa25;
    private javax.swing.JTextField txttentativa26;
    private javax.swing.JTextField txttentativa27;
    private javax.swing.JTextField txttentativa28;
    private javax.swing.JTextField txttentativa29;
    // End of variables declaration//GEN-END:variables
}
